PROJECT_OBJECTFILES += $(TIKIDB_PATH)/database/dbms.o
PROJECT_OBJECTFILES += $(TIKIDB_PATH)/database/dbms-operations.o
PROJECT_OBJECTFILES += $(TIKIDB_PATH)/database/db.o
PROJECT_OBJECTFILES += $(TIKIDB_PATH)/database/db-operations.o
PROJECT_OBJECTFILES += $(TIKIDB_PATH)/database/db-list.o

PROJECT_LIBRARIES += $(TIKIDB_PATH)/database/dbms.o
PROJECT_LIBRARIES += $(TIKIDB_PATH)/database/dbms-operations.o
PROJECT_LIBRARIES += $(TIKIDB_PATH)/database/db.o
PROJECT_LIBRARIES += $(TIKIDB_PATH)/database/db-operations.o
PROJECT_LIBRARIES += $(TIKIDB_PATH)/database/db-list.o

