include $(TIKIDB_PATH)/querymanager/Makefile

PROJECT_OBJECTFILES += $(TIKIDB_PATH)/queryresolver/queryresolver.o
PROJECT_OBJECTFILES += $(TIKIDB_PATH)/queryresolver/queryresolver-util.o

PROJECT_LIBRARIES += $(TIKIDB_PATH)/queryresolver/queryresolver.o
PROJECT_LIBRARIES += $(TIKIDB_PATH)/queryresolver/queryresolver-util.o