/* Generated By:JavaCC: Do not edit this line. TikiDBParserTokenManager.java */
package de.tud.dvs.parser.javacc;
import java.util.Vector;
import de.tud.dvs.parser.Tools;
import de.tud.dvs.parser.operations.*;

/** Token Manager. */
public class TikiDBParserTokenManager implements TikiDBParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 50;
            return 114;
         }
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 50;
            return 47;
         }
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 50;
            return 3;
         }
         if ((active0 & 0x400010000000L) != 0L)
         {
            jjmatchedKind = 50;
            return 92;
         }
         if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 50;
            return 75;
         }
         if ((active0 & 0x33f7edf40000L) != 0L)
         {
            jjmatchedKind = 50;
            return 32;
         }
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 50;
            return 17;
         }
         if ((active0 & 0x800L) != 0L)
            return 12;
         if ((active0 & 0x800000000L) != 0L)
         {
            jjmatchedKind = 50;
            return 96;
         }
         if ((active0 & 0x400L) != 0L)
            return 10;
         return -1;
      case 1:
         if ((active0 & 0x400010000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 1;
            return 124;
         }
         if ((active0 & 0x80000000000L) != 0L)
            return 74;
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 1;
            return 46;
         }
         if ((active0 & 0x800800400000L) != 0L)
            return 32;
         if ((active0 & 0x37f7edbc0000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 1;
            return 32;
         }
         return -1;
      case 2:
         if ((active0 & 0x77f7ffbc0000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 2;
            return 32;
         }
         return -1;
      case 3:
         if ((active0 & 0x73f4ffb40000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 3;
            return 32;
         }
         if ((active0 & 0x40300080000L) != 0L)
            return 32;
         return -1;
      case 4:
         if ((active0 & 0x400300000L) != 0L)
            return 32;
         if ((active0 & 0x73f0ff840000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 4;
            return 32;
         }
         return -1;
      case 5:
         if ((active0 & 0x53903a000000L) != 0L)
         {
            if (jjmatchedPos != 5)
            {
               jjmatchedKind = 50;
               jjmatchedPos = 5;
            }
            return 32;
         }
         if ((active0 & 0x2060c5840000L) != 0L)
            return 32;
         return -1;
      case 6:
         if ((active0 & 0x43102a000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 6;
            return 32;
         }
         if ((active0 & 0x108014000000L) != 0L)
            return 32;
         return -1;
      case 7:
         if ((active0 & 0x430020000000L) != 0L)
         {
            if (jjmatchedPos != 7)
            {
               jjmatchedKind = 50;
               jjmatchedPos = 7;
            }
            return 32;
         }
         if ((active0 & 0x100a000000L) != 0L)
            return 32;
         return -1;
      case 8:
         if ((active0 & 0x430020000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 8;
            return 32;
         }
         if ((active0 & 0x8000000L) != 0L)
            return 32;
         return -1;
      case 9:
         if ((active0 & 0x430020000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 9;
            return 32;
         }
         return -1;
      case 10:
         if ((active0 & 0x410020000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 10;
            return 32;
         }
         if ((active0 & 0x20000000000L) != 0L)
            return 32;
         return -1;
      case 11:
         if ((active0 & 0x410020000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 11;
            return 32;
         }
         return -1;
      case 12:
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 12;
            return 32;
         }
         if ((active0 & 0x410000000000L) != 0L)
            return 32;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa1_0(0x200L);
      case 40:
         return jjStopAtPos(0, 54);
      case 41:
         return jjStopAtPos(0, 55);
      case 44:
         return jjStopAtPos(0, 56);
      case 60:
         return jjStartNfaWithStates_0(0, 11, 12);
      case 62:
         return jjStartNfaWithStates_0(0, 10, 10);
      case 91:
         return jjStopAtPos(0, 57);
      case 93:
         return jjStopAtPos(0, 58);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x800000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x40000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x20200000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x2000000000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x80000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa1_0(0x200000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x80000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x2000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x400010000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa1_0(0x800000000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x108001000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0xa0000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x21550c840000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x40000000000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa1_0(0x100000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 61:
         if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(1, 9);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x8200800000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x241a5040000L);
      case 70:
      case 102:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 47, 32);
         break;
      case 72:
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L);
      case 78:
      case 110:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 43, 74);
         break;
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x510010000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x40280000L);
      case 83:
      case 115:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(1, 35, 32);
         break;
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x1008000000L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000L);
      case 89:
      case 121:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(1, 22, 32);
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x1008000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x400010000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x40100000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000040000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x80800000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x4104000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x400280000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x40020000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(3, 33, 32);
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000L);
      case 68:
      case 100:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(3, 32, 32);
         break;
      case 69:
      case 101:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 42, 32);
         return jjMoveStringLiteralDfa4_0(active0, 0x600012040000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000L);
      case 77:
      case 109:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 19, 32);
         break;
      case 79:
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0xa0000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x400800000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000100000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x700c000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa5_0(active0, 0x420010000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x11008040000L);
      case 69:
      case 101:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(4, 20, 32);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(4, 34, 32);
         break;
      case 71:
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0xc005000000L);
      case 80:
      case 112:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(4, 21, 32);
         break;
      case 82:
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x2042000000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000L);
      case 68:
      case 100:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(5, 24, 32);
         break;
      case 69:
      case 101:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(5, 23, 32);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(5, 30, 32);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(5, 31, 32);
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 45, 32);
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x32000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x101008000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000000L);
      case 82:
      case 114:
         if ((active0 & 0x4000000000L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000L);
      case 83:
      case 115:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 37, 32);
         break;
      case 84:
      case 116:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(5, 18, 32);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000000L);
      case 68:
      case 100:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(6, 28, 32);
         else if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 39, 32);
         break;
      case 77:
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000L);
      case 78:
      case 110:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 44, 32);
         break;
      case 79:
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x420000000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0x1008000000L);
      case 83:
      case 115:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(6, 26, 32);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000000L);
      case 69:
      case 101:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(7, 25, 32);
         else if ((active0 & 0x1000000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000000L);
      case 83:
      case 115:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(8, 27, 32);
         break;
      case 85:
      case 117:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         return jjMoveStringLiteralDfa10_0(active0, 0x10000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa10_0(active0, 0x400000000000L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000000L);
      case 69:
      case 101:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 41, 32);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa11_0(active0, 0x400000000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa11_0(active0, 0x10000000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 75:
      case 107:
         return jjMoveStringLiteralDfa12_0(active0, 0x20000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa12_0(active0, 0x10000000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa12_0(active0, 0x400000000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 40, 32);
         return jjMoveStringLiteralDfa13_0(active0, 0x20000000L);
      case 78:
      case 110:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 46, 32);
         break;
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 89:
      case 121:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(13, 29, 32);
         break;
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 124;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 124:
               case 32:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(32);
                  break;
               case 3:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(32);
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(32);
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(32);
                  break;
               case 92:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(32);
                  break;
               case 75:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(32);
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(32);
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(32);
                  break;
               case 96:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(32);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(34);
                  }
                  else if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(34);
                  else if (curChar == 61)
                     jjAddStates(0, 2);
                  else if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 12;
                  else if (curChar == 62)
                     jjstateSet[jjnewStateCnt++] = 10;
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 1;
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 27;
                  else if (curChar == 61)
                  {
                     if (kind > 8)
                        kind = 8;
                  }
                  else if (curChar == 38)
                  {
                     if (kind > 5)
                        kind = 5;
                  }
                  break;
               case 114:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(32);
                  break;
               case 1:
                  if (curChar == 38 && kind > 5)
                     kind = 5;
                  break;
               case 2:
                  if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 9:
               case 109:
                  if (curChar == 61 && kind > 8)
                     kind = 8;
                  break;
               case 10:
                  if (curChar == 61 && kind > 12)
                     kind = 12;
                  break;
               case 11:
                  if (curChar == 62)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 61 && kind > 13)
                     kind = 13;
                  break;
               case 13:
                  if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) != 0L && kind > 48)
                     kind = 48;
                  break;
               case 30:
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 33:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(34);
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAdd(34);
                  break;
               case 108:
                  if (curChar == 61)
                     jjAddStates(0, 2);
                  break;
               case 110:
                  if (curChar == 62 && kind > 12)
                     kind = 12;
                  break;
               case 111:
                  if (curChar == 60 && kind > 13)
                     kind = 13;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 124:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAdd(32);
                  }
                  if ((0x10000000100000L & l) != 0L)
                  {
                     if (kind > 7)
                        kind = 7;
                  }
                  if ((0x10000000100000L & l) != 0L)
                  {
                     if (kind > 7)
                        kind = 7;
                  }
                  break;
               case 3:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAdd(32);
                  }
                  if ((0x4000000040000L & l) != 0L)
                  {
                     if (kind > 6)
                        kind = 6;
                  }
                  break;
               case 47:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAdd(32);
                  }
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 54;
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 46:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAdd(32);
                  }
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 53;
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 92:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAdd(32);
                  }
                  if ((0x800000008000L & l) != 0L)
                     jjCheckNAdd(91);
                  if ((0x800000008000L & l) != 0L)
                     jjCheckNAdd(91);
                  break;
               case 75:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAdd(32);
                  }
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 88;
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 74:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAdd(32);
                  }
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 87;
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 17:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAdd(32);
                  }
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 96:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAdd(32);
                  }
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 106;
                  else if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 95;
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAdd(32);
                  }
                  else if (curChar == 126)
                  {
                     if (kind > 7)
                        kind = 7;
                  }
                  else if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 6;
                  if ((0x10000000100000L & l) != 0L)
                     jjAddStates(3, 4);
                  else if ((0x200000002L & l) != 0L)
                     jjAddStates(5, 7);
                  else if ((0x400000004000L & l) != 0L)
                     jjAddStates(8, 9);
                  else if ((0x20000000200L & l) != 0L)
                     jjAddStates(10, 11);
                  else if ((0x100000001000L & l) != 0L)
                     jjAddStates(12, 13);
                  else if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 25;
                  else if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 17;
                  else if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 3;
                  else if (curChar == 124)
                  {
                     if (kind > 6)
                        kind = 6;
                  }
                  break;
               case 114:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAdd(32);
                  }
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 122;
                  else if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 4:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 5:
               case 6:
                  if (curChar == 124 && kind > 6)
                     kind = 6;
                  break;
               case 7:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 126)
                     kind = 7;
                  break;
               case 14:
                  if ((0x2000000020L & l) != 0L && kind > 14)
                     kind = 14;
                  break;
               case 15:
                  if ((0x8000000080000L & l) != 0L)
                     jjCheckNAdd(14);
                  break;
               case 16:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 18:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if ((0x200000002000000L & l) != 0L && kind > 17)
                     kind = 17;
                  break;
               case 20:
                  if ((0x10000000100000L & l) != 0L)
                     jjCheckNAdd(19);
                  break;
               case 21:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 23:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if ((0x100000001000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 28:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 29:
                  if ((0x7e0000007eL & l) != 0L && kind > 48)
                     kind = 48;
                  break;
               case 31:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(32);
                  break;
               case 32:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(32);
                  break;
               case 35:
                  if ((0x100000001000L & l) != 0L)
                     jjAddStates(12, 13);
                  break;
               case 36:
                  if ((0x10000000100000L & l) != 0L && kind > 17)
                     kind = 17;
                  break;
               case 37:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 41:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 42:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 43:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 44:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 48:
                  if ((0x4000000040000L & l) != 0L && kind > 17)
                     kind = 17;
                  break;
               case 49:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 50:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 51:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 52:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if ((0x20000000200L & l) != 0L)
                     jjAddStates(10, 11);
                  break;
               case 57:
                  if ((0x2000000020L & l) != 0L && kind > 17)
                     kind = 17;
                  break;
               case 58:
               case 115:
                  if ((0x4000000040000L & l) != 0L)
                     jjCheckNAdd(57);
                  break;
               case 59:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 60:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 61:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 63:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 64:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 65:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 67:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 68:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 69:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 73:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 76:
                  if ((0x8000000080L & l) != 0L)
                     jjCheckNAdd(57);
                  break;
               case 77:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 78:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 79:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 82:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 84:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 85:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 87:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 90:
                  if ((0x400000004000L & l) != 0L)
                     jjAddStates(8, 9);
                  break;
               case 91:
                  if ((0x10000000100000L & l) != 0L && kind > 7)
                     kind = 7;
                  break;
               case 93:
                  if ((0x800000008000L & l) != 0L)
                     jjCheckNAdd(91);
                  break;
               case 94:
                  if ((0x200000002L & l) != 0L)
                     jjAddStates(5, 7);
                  break;
               case 95:
                  if ((0x1000000010L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 97:
                  if ((0x100000001000000L & l) != 0L && kind > 17)
                     kind = 17;
                  break;
               case 98:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (curChar == 95)
                     jjCheckNAdd(19);
                  break;
               case 104:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 105:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 112:
                  if ((0x10000000100000L & l) != 0L)
                     jjAddStates(3, 4);
                  break;
               case 113:
                  if ((0x20000000200000L & l) != 0L)
                     jjCheckNAdd(14);
                  break;
               case 116:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 120:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 123:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 124 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   109, 110, 111, 114, 123, 96, 102, 107, 92, 93, 75, 89, 47, 55, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, "\41\75", "\76", "\74", 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
"\50", "\51", "\54", "\133", "\135", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x7e5fffffffe7fe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[124];
private final int[] jjstateSet = new int[248];
protected char curChar;
/** Constructor. */
public TikiDBParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public TikiDBParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 124; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
