#include $(TIKIDB_PATH)/treeforming/Makefile

PROJECT_OBJECTFILES += $(TIKIDB_PATH)/querymanager/querymanager.o
PROJECT_OBJECTFILES += $(TIKIDB_PATH)/querymanager/querymanager-qidlist.o
PROJECT_OBJECTFILES += $(TIKIDB_PATH)/querymanager/query-parser.o

PROJECT_LIBRARIES += $(TIKIDB_PATH)/querymanager/querymanager.o
PROJECT_LIBRARIES += $(TIKIDB_PATH)/querymanager/querymanager-qidlist.o
PROJECT_LIBRARIES += $(TIKIDB_PATH)/querymanager/query-parser.o